---
title: "chp. 7 EDA"
format: html
editor: visual
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
library(nycflights13)
library(gridExtra)
library(modelr)
library(grid)
library(ggplotify)
library(vtable)
library(flextable)
```


## EDA

```{r}
#| eval: false
# create a bib file for the R packages 
# used in this document
# Note! Needs to do a `touch eda.bib` in terminal before first run
# else stops when bibliography: "eda.bib" not found in YAML
packs <- c("tidyverse", "nycflights13", "gridExtra",
           "modelr", "grid", "ggplotify", "vtable", "flextable")
knitr::write_bib(
  packs,
  file = "eda.bib"
  )
rm(packs)
```

```{r}
heights <- modelr::heights
```

```{r}
heights |> 
  ggplot(mapping =aes(x = height, y = income)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
heights |> 
  filter(income < 300000) |> 
  ggplot(mapping =aes(x = height, y = income)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
heights %>% 
  mutate(
    edu_fac = cut(education, 
                  breaks = c(0, 12, 14, 16, 21), 
                  labels = c("NotHS", "NotTC", "NotC", "C+"),
                  right = FALSE) 
  ) %>% 
  filter(income < 1) %>%
  select(sex, edu_fac) %>%
  group_by(sex) %>%
  table()
```

```{r}
heights %>% 
  filter(income > 0 & !is.na(weight) & !is.na(afqt) & !is.na(education)) %>%
  ggplot() +
  geom_point(mapping = aes(x = education, y = income), alpha = 0.05)
```

```{r}
# using drop_na() makes it easier
heights |> 
  drop_na() |> 
  filter(income > 0) %>%
  ggplot() +
  geom_point(mapping = aes(x = education, y = income), alpha = 0.05)
```

